if [ "${XDG_SESSION_TYPE}" = "tty" ] && [ "${XDG_VTNR}" = "1" ] && [ -z "${SSH_TTY}" ] && [ -z "${SSH_CONNECTION}" ]; then
  export XMODIFIERS=@im=fcitx
  export GTK_IM_MODULE=fcitx
  export QT_IM_MODULE=fcitx
  export SWAY_UNSUPPORTED_GPU="true"
  sway |& tee /tmp/sway.log
fi
