[theme]
theme = "modern"

[icons]
icons = "material-nf"

# [[block]]
# block = "focused_window"
# format = " $title.str(max_w:40)"

[[block]]
block = "custom"
json = true
command = '''
count=$(systemctl --failed --no-legend --no-pager 2>/dev/null | wc -l)
if [ "$count" -eq 0 ]; then
  echo '{"state":"Idle","text":""}'
else
  echo "{\"state\":\"Critical\",\"text\":\"$count failed systemd units\"}"
fi'''
interval = 60
hide_when_empty = true

[[block]]
block = "disk_iostats"
device = "nvme1n1"
format = " $speed_write "
interval = 1

[[block]]
block = "cpu"
format = " CPU $utilization ($frequency) "
interval = 1

[[block]]
block = "temperature"
chip = "coretemp-isa-*"
format = " CORE $max "
interval = 1

[[block]]
block = "memory"
format = " RAM $mem_used_percents.eng(w:2) "
interval = 2

[[block]]
block = "custom"
command = "sensors -u nvme-pci-e100 2>/dev/null | sed -n '/temp1_input/s/.* //p' | xargs printf 'SN770 %.0f°'"
interval = 10
format = " $text "

[[block]]
block = "custom"
command = "sensors -u nvme-pci-e200 2>/dev/null | sed -n '/temp1_input/s/.* //p' | xargs printf 'SN7100 %.0f°'"
interval = 10
format = " $text "

[[block]]
block = "nvidia_gpu"
format = " GPU $temperature "
interval = 1

[[block]]
block = "sound"
driver = "pulseaudio"
format = " $icon {$volume|Muted} "

[[block]]
block = "custom"
command = "fcitx5-remote -n"
interval = 1
format = " $text "

[[block]]
block = "time"
interval = 10
format = " $timestamp.datetime(f:'%a %m/%d %R') "
